### ISSUE TITLE
💡 question: what does this do?

### ISSUE THREAD

**Issue by tdiprima** [kazupon/git-commit-message-convention#13]
Hi @kazupon.  This looks really neat and I want to use it.  Is this package meant to be installed globally, and then it checks your commit messages to make sure it follows the convention?  Would you still use command `git commit -m ...`, and that's what it checks?

Thanks in advance.

**Comment by kazupon** [comment]
Hi!

This package is intended to be used in conjunction with conventional-commits.
https://www.conventionalcommits.org/en/v1.0.0/

This commit message convention is an extension of conventional-commits, and is mainly for my own use in OSS development.
For this reason, I am not sure if this package is a good match for you.
It is recommended to try it out in your side project.

Thanks!
