### ISSUE TITLE
Do you have any suggestion ?

### ISSUE THREAD

**Issue by theapache64** [kazupon/git-commit-message-convention#7]
Hey, I've created a small cli program to build commit message interactively by following the instructions given in this project. It does the purpose and works perfectly fine.

https://github.com/theapache64/ugh

What do you think ? Feel free to show me any error, bug or anti-patterns.

**Comment by gbdsantos** [comment]
Hi!
My suggestion is that it is possible to add translations in other languages to your repository.

For example, a file called "README_PT-BR.md" and add a flag linked to that file in the main README.

I'm creating a repository like yours in brazilian portuguese, for developers who have difficulties with English.
